VideoTarzan/VideoTarzan/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace VideoTarzan.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VideoTarzan/VideoTarzan/Controllers/PeliculasController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using VideoTarzan.Context;
using VideoTarzan.Models;

namespace VideoTarzan.Controllers
{
    [Authorize]
    public class PeliculasController : Controller
    {
        private VideoContext db = new VideoContext();

        // GET: Peliculas
        public ActionResult Index()
        {
            return View(db.pelicula.ToList());
        }

        // GET: Peliculas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // GET: Peliculas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Peliculas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPelicula,titulo,descripcion,listaActores,director,costoAlquiler,cantidadInventario")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.pelicula.Add(pelicula);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pelicula);
        }

        // GET: Peliculas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPelicula,titulo,descripcion,listaActores,director,costoAlquiler,cantidadInventario")] Pelicula pelicula)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pelicula).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pelicula);
        }

        // GET: Peliculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pelicula pelicula = db.pelicula.Find(id);
            if (pelicula == null)
            {
                return HttpNotFound();
            }
            return View(pelicula);
        }

        // POST: Peliculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pelicula pelicula = db.pelicula.Find(id);
            db.pelicula.Remove(pelicula);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VideoTarzan/VideoTarzan/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VideoTarzan/VideoTarzan/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VideoTarzan/VideoTarzan/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>VideoTarzan</h1>
    <p class="lead">VideoTarzan una tienda online donde puede adquirir tus peliculas</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2><img src="https://drama.fandom.com/es/wiki/GFRIEND?file=EOuRml2UEAARQcI.jpg"></h2>
        <p>
            Parasitos.

            Tanto Gi Taek como su familia están sin trabajo. Cuando su hijo mayor, Gi Woo, empieza a recibir clases particulares en la adinerada casa de Park, las dos familias, que tienen mucho en común pese a pertenecer a dos mundos totalmente distintos, comienzan una relación de resultados imprevisibles
        </p>
        <p>@Html.ActionLink("Ver", "Index", "Peliculas")
    </div>
    <div class="col-md-4">
        <h2><img src="https://www.google.com/search?q=joker+poster&tbm=isch&ved=2ahUKEwiJhMWx-eDnAhXHBVkKHZsmC1gQ2-cCegQIABAA&oq=joker+poster&gs_l=img.3..0l10.1035.2009..2185...0.0..0.144.880.0j7......0....1..gws-wiz-img.......0i67.xC5QHcI6bnI&ei=OOlOXomIOseL5AKbzazABQ#imgrc=z7hezWTv9usCcM"></h2>
        <p>
            Joker

            Arthur Fleck adora hacer reír a la gente, pero su carrera como comediante es un fracaso. El repudio social, la marginación y una serie de trágicos acontecimientos lo conducen por el sendero de la locura y, finalmente, cae en el mundo del crimen
        </p>
        <p>@Html.ActionLink("Ver", "Index", "Peliculas")</p>
    </div>
    <div class="col-md-4">
        <h2><img src="https://www.google.com/search?q=infinity+war+2+avenger+end+game&tbm=isch&ved=2ahUKEwj53bGz-eDnAhUOXVkKHRTaAnYQ2-cCegQIABAA&oq=avenger+end+game+2&gs_l=img.1.0.0i8i30l3j0i24.13930.17669..18141...0.0..0.139.1644.0j13......0....1..gws-wiz-img.......35i39j0i67j0.ftqginZr9Gg&ei=POlOXvnPMo665QKUtIuwBw#imgrc=_TRnVg7mD1ea0M"></h2>
        <p>
            Avengers EndGame.

            Los Vengadores restantes deben encontrar una manera de recuperar a sus aliados para un enfrentamiento épico con Thanos, el malvado que diezmó el planeta y el universo.
        </p>
        <p>@Html.ActionLink("Ver", "Index", "Peliculas")
    </div>
</div>